site/base/urls.py
from django.contrib import admin
from django.urls import include, path
from base import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/books/urls.py
from django.urls import path
from django.views.generic import TemplateView
from books.views import index, books, detail


app_name = 'books'

urlpatterns = [
    #path('', TemplateView.as_view(template_name='base.html'), name='index'),
    path('', index, name='index'),
    path('category/<slug:category_slug>/', books, name='category'),
    path('<slug:slug_name>/', detail, name='detail')
]

site/books/models.py
from django.db import models
from django.core.validators import MaxValueValidator



class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    slug = models.SlugField(max_length=64, unique=True, verbose_name='url')

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    

class Book(models.Model):
    name = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(max_length=64, unique=True, verbose_name='url')
    author = models.ForeignKey(
        to='Author',
        on_delete=models.CASCADE,
        related_name='books'
    )
    description = models.TextField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.PositiveIntegerField(blank=True, default=0, validators=[MaxValueValidator(99)])
    quantity = models.PositiveSmallIntegerField()
    category = models.ForeignKey(
        to=Category,
        on_delete=models.PROTECT,
        related_name='books',
    )

    class Meta:
        db_table = 'book'
        verbose_name = 'book'
        verbose_name_plural = 'books'
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=32)
    second_name = models.CharField(max_length=32)

    class Meta:
        db_table = 'author'
        verbose_name = 'author'
        verbose_name_plural = 'authors'
    
    def __str__(self):
        return f'{self.first_name} {self.second_name}'

site/books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator


from books.models import Category, Book


def index(request) -> HttpResponse:

    return render(
        request,
        'books/index.html',
        {'title': 'HomePage', 'content': 'BookStore'}
    )

def books(request, category_slug) -> HttpResponse:
    books = Book.objects.filter(category__slug=category_slug)

    page_number = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale')
    order_by = request.GET.get('order_by')

    if order_by and order_by != 'default':
        books = books.order_by(order_by)
    if on_sale:
        books = books.filter(discount__gt=0)

    paginator = Paginator(books, 3)
    current_page = paginator.get_page(page_number)

    return render(
        request,
        'books/books.html',
        {'page_obj': current_page}
    )

def detail(request, slug_name):
    book = get_object_or_404(Book, slug=slug_name)
    return render(
        request,
        'books/detail.html',
        {'book': book}
    )

site/books/templates/books/books.html
{% extends "base.html" %}

{% block title %}   
    {{ title }}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-1">
        <div class="col-lg-2">
            <!-- PLUG -->
        </div>
        <div class="col-lg-10">
            <div class="row">
                {% include "includes/filter.html" %}

                {% for book in page_obj %}
                    {% include "includes/card_book.html" %}
                {% endfor %}
            </div>
            {% include "includes/pagination.html" %}
        </div>
    </div>
</div>
{% endblock content %}

site/books/templates/books/detail.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}   
    {{ title }}
{% endblock title %}

{% block content %}
<div class="col-lg-10">
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">

                <div class="col-md-4">
                    <img src="{{ book.image.url }}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: {{ book.id|fillzero }}</p>
                </div>

                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ book.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ book.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <p class="card-text">Price: <strong>{{ book.price }} P</strong></p>
                <h5 class="card-title">{{ book.name }}</h5>
                <p class="card-text">{{ book.description }}</p>
                <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

site/books/templates/books/index.html
{% extends "base.html" %}

{% block title %}   
    HomePage
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- PLUG -->
            </div>
            <div class="col-lg-10">
                <h1 class="mt-5 pt-5"><strong>Wellcom to BookStore</strong></h1>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; BookStore For You 2024</p>
        </div>
    </footer>
{% endblock footer %}

site/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my_css.css' %}">
    <!-- Стиль footer-a для главной страницы -->
    <link rel="stylesheet" href="{% static 'css/my_footer_css.css' %}">
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    
    {% include "includes/header.html" %}
    
    <section>
        {% include "includes/catalog.html" %}
        {% block content %}{% endblock content %}
    </section>

    {% block footer %}{% endblock footer %}

    <script src="{% static 'js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-events.js' %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

site/templates/includes/card_book.html
{% load static %}
{% load custom_tags %}
<div class="col-lg-4 col-md-6 p-4">
    <div class="card border-primary rounded custom-shadow">

        <img src="{{ book.image.url }}" class="card-img-top" >
        <div class="card-body">
            <a href="{% url 'books:detail' book.slug %}">
                <p class="card-title">{{ book.name }}</p>
            </a>
            <p class="card-text text-truncate">{{ book.description }}</p>
            <p class="product_id">id: {{ book.id|fillzero }}</p>
            <div class="d-flex justify-content-between">
                
                 
                
                {% if book.discount %}
                    <span class="badge bg-warning text-dark">Скидка {{ book.discount }} %</span>
                    <p><s>{{ book.price }}</s> P</p>
                {% endif %}
                <p><strong>{{ book.price }} P</strong></p>
                <!-- <p><strong>100.00 $</strong></p> -->
                <a href="#" class="btn add-to-cart">
                    <img class="mx-1" src="{% static "icons/cart-plus.svg" %}" alt="Catalog Icon"
                        width="32" height="32">
                </a>
            </div>
        </div>
    </div>
</div>

site/templates/includes/catalog.html
{% load static %}
{% load custom_tags %}

<div class="container">
    <!-- Каталог и корзина с фиксированным расположением на странице -->
    <div class="row mt-1 position-fixed z-3">
        <!-- Каталог -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Каталог
                <img class="mx-1" src="{% static 'icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                    height="16">
            </button>
            <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                {% all_categories as categories %}
                {% for category in categories %}
                <li><a class="dropdown-item text-white" href="{% url "books:category" category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <!-- Значек корзины, вызывает модальное окно -->
        <div>
            <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                aria-expanded="false">
                <img class="mx-1" src="{% static 'icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24"
                    height="24">
                <span id="goods-in-cart-count">0</span>
            </button>
        </div>
        <!-- Разметка модального окна корзины -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <h3 class="text-center mb-4">Корзина</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            <div class="card mb-3 text-bg-light shadow-lg">
                                <div class="card-header">
                                    <h5 class="card-title">Товар</h5>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                        <div class="row text-center">
                                            <div class="col p-0">
                                                <div class="input-group">
                                                    <span class="input-group-btn">
                                                        <button type="button" class="btn btn-dark btn-sm decrement"
                                                            data-cart-id="" data-cart-change-url="">-</button>
                                                    </span>
                                                    <input type="text" class="form-control number" value="1"
                                                        readonly>
                                                    <span class="input-group-btn">
                                                        <button type="button" class="btn btn-dark btn-sm increment"
                                                            data-cart-id="" data-cart-change-url="">+</button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="col p-0">
                                                <p>x 100.00 = </p>
                                            </div>
                                            <div class="col p-0"><strong>100.00 $</strong></div>
                                            <div class="col p-0">
                                                <a href="#" class="remove-from-cart" data-cart-id="">
                                                    <img class="mx-1" src="{% static 'icons/trash3-fill.svg' %}"
                                                        alt="Catalog Icon" width="16" height="16">
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="card mb-3 shadow-lg">
                                <div class="card-footer">
                                    <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                    <h4 class="float-left"><strong>100.00 $</strong></h4>
                                </div>
                            </div>
                            <!-- Закончилась разметка корзины -->
                        </div>
                        <a class="btn btn-dark" href="orders/create_order.html">
                            Оформить заказ
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Закончилась разметка модального окна -->
    </div>
</div>

site/templates/includes/filter.html
<div class="dropdown mb-2">
    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Фильтры
    </button>

    <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
            {% if request.GET.on_sale == 'on' %} checked {% endif %}>
            <input type="hidden" name="q" value="request.GET.q">
            <label class="form-check-label" for="flexCheckDefault">
                Товары по акции
            </label>
        </div>
        <p class="text-white mx-3 mt-3">Сортировать:</p>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" 
            {% if not request.GET.order_by or request.GET.order_by == 'default' %} checked {% endif %}>
            <label class="form-check-label" for="flexRadioDefault1">
                По умолчанию
            </label>
        </div>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
            {% if request.GET.order_by == 'price' %} checked {% endif %}>
            <label class="form-check-label" for="flexRadioDefault2">
                От дешевых к дорогим
            </label>
        </div>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
            {% if request.GET.order_by == '-price' %} checked {% endif %}>
            <label class="form-check-label" for="flexRadioDefault3">
                От дорогих к дешевым
            </label>
        </div>
        <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
    </form>
</div>

site/templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="{% url "books:index" %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Информация
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                            <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                            <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="users/login.html">Войти</a>
                    </li>
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Мой профиль
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                            <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a>
                            </li>
                            <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Admin Panel</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>
</header>

site/templates/includes/pagination.html
{% load custom_tags %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
              <a class="page-link"
              href="{% if page_obj.has_previous %}?{% extend_param page=page_obj.previous_page_number %}{% endif %}">Previous</a>
            </li>
            {% for page in page_obj.paginator.page_range  %}
            {% if page >= page|add:-2 and page <= page|add:2 %}
              <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                <a class="page-link" href="?{% extend_param page=page %}">{{ page }}</a></li>
            {% endif %}
            {% endfor %}

            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
              <a class="page-link"
              href="{% if page_obj.has_next %}?{% extend_param page=page_obj.next_page_number %}{% endif %}">Next</a>
            </li>
        </div>
    </ul>
</nav>